Add optional version change argument to publish-releasenotes-on-slack
5minds/ci_tools pull request #84
Opened 2020-10-08 13:34 UTC by alexanderkasten

## Changes

1. Add --addVersionChange argument to getReleaseAnnouncement
2. Add package updates to release announcement

Example:
```
*@process-engine/ci_tools v3.1.0-alpha.10 was released!*

The new version includes the following changes:

- Betarelease v3.1.0 beta.2
- Increase total amount of retries with npm view before failing ensureVersionIsAvailable
- 🔒 Fix security vulnerabilities
- ✨ Add python and .NET support to create-release-announcement
- ✨ Add --release-channel-(name|number) option for get-version
- 🐛 Don't use dev dependencies in runtime code
- ✨ Add support for Python projects
- ✨ Add new command to replace dist-tags with real versions

The following dependencies were updated:

- node-fetch was updated from ^2.6.0 to ^2.6.1
,- mocha was updated from ^6.1.4 to ^8.1.3

*For a more detailed changelog have a look at:* http://github.com/process-engine/ci_tools/releases/tag/v3.1.0-alpha.10
```

Woher das Kommatar in der mocha Zeile kommt weiß ich im Moment noch nicht. Ich konnte jetzt leider nicht mehr weiter debuggen da `API rate limit exceeded for 91.9.121.4. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`.

## Issues

PR: #NumberOfThisPR

## How to test the changes

Branch auschecken und `node dist/ci_tools.js publish-releasenotes-on-slack --addVersionChange node-fetch --addVersionChange mocha` ausführen.

2020-10-08 14:21 UTC, NullEnt1ty requested changes

2020-10-08 14:21 UTC, NullEnt1ty commented on src/commands/internal/create-release-announcement.ts
> +})}
Die zweite und alle weiteren Zeilen fangen mit einem Komma an, weil `.map` ein Array zurückgibt. Wird dieses in einen Template String gesteckt, wird `toString()` auf dem Array aufgerufen. Das Ergebnis ist eine Verkettung mit Kommata. Es fehlt ein [join](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) nach `map`.

<img width="431" alt="grafik" src="https://user-images.githubusercontent.com/966433/95469256-bcebd200-097f-11eb-9c08-d6d3d09324a3.png">

2020-10-08 14:21 UTC, NullEnt1ty commented on src/commands/internal/create-release-announcement.ts
> +${packageVersionChangeArray.length !== 0 ? 'The following dependencies were updated:' : ''}
Vielleicht sollte die Variable auch "dependencies" im Namen tragen. Ich hab mich bei meiner Code-Review bis zu dieser Stelle gefragt, um welche Pakete es genau geht.

Wie wär's mit "changedDependencies"? Man könnte natürlich auch noch das Suffix "Array" anhängen, falls der Plural "dependencies" nicht eindeutig genug impliziert, dass es sich um etwas Iterierbares handelt.

2020-10-08 14:21 UTC, NullEnt1ty commented on src/commands/internal/create-release-announcement.ts
> +function getPackageVersionObject(versionChanges: string[], packageName: string): any {
Ich sehe eine return-Anweisung mit einer ziemlich klaren Objektstruktur. Daher bitte kein "any" verwenden, sondern einen Typ definieren.

2020-10-08 14:21 UTC, NullEnt1ty commented on src/commands/publish-releasenotes-on-slack.ts
> +  );
Wenn ich mich nicht irre, symbolisieren die eckigen Klammern hier optionale Argumente. Da "--mode" und "--addVersionChange" beide gleichzeitig verwendet werden können, sollte auch eine "Usage"-Zeile dafür reichen. Ich meine, das haben wir bei den anderen Befehlen auch so gemacht, oder?

2020-10-08 14:25 UTC, alexanderkasten commented on src/commands/internal/create-release-announcement.ts
> +})}
Danke, hätte sicherlich noch gedauert bis ich das gefunden hätte 👍

2020-10-09 06:35 UTC, rrrene requested changes
Besprechen wir am Montag

2020-10-22 05:42 UTC, rrrene requested changes
An dieser Stelle habe ich mit anderen Worten den Grad an Sorgfalt in diesem PR zusammengefasst (ist in der Bearbeitungshistorie nachzulesen). Diese Worte konnte man als persönliche Vorhaltung empfinden. Ich habe die Sätze daher entfernt. 

Die angesprochenen Sorgfaltsmängel existieren unabhängig davon.

2020-10-22 05:42 UTC, rrrene commented on src/commands/publish-releasenotes-on-slack.ts
> +--addVersionChange    adds version changes to the changelog, it can be used several times
Meiner Wahrnehmung nach sind Kommandozeilen-Switches/Options immer mit Bindestrichen strukturiert (`git pull --no-ff`, `npm install --save-dev`, `eslint --fix-dry-run`).

Ich finde es schade, dass in den vorangegangenen Reviews sowas offensichtliches nicht auffällt.

2020-10-22 05:42 UTC, rrrene commented on src/git/git.ts
> +export function getStartCommit(startDate: string, branch: string): string {
Was ist "start"? Bitte ein bisschen Mühe bei der Namensfindung geben. Wahrscheinlich wolltest du eine Funktion erstellen, die den zeitlich ersten Commit nach einem gegebenen Datum zurückliefert. `getStartCommit` sagt das nicht aus.

2020-10-22 05:42 UTC, rrrene commented on src/git/git.ts
> +export function getDiffFromStartToCurrentHead(startCommit: string, filename: string): string {
Warum kommt hier das Wort "start" überhaupt vor?

Wahrscheinlich wolltest du eine Funktion erstellen, die den Diff von einem gegebenen Commit bis zu `HEAD` zurückliefert. Dann nenn die Funktion doch bitte auch so.

2020-10-22 05:42 UTC, rrrene commented on src/commands/internal/create-release-announcement.ts
> +  );
Hier steht exakt der gleiche Code für `previous` und `current` mit der Unterscheidung anhand von `-` bzw. `+`.

Bitte lager das in eine Funktion aus.

2020-10-22 05:42 UTC, rrrene commented on src/commands/internal/create-release-announcement.ts
> +      }
Das hier versagt, wenn ich einen Package-Namen angebe, der nicht vorkommt, und "warnt" mich auch nicht, wenn die Dependency entfernt wird, sondern endet in einem "silent fail" (es findet sich nirgendwo ein Hinweis, dass das, was ich angegeben habe, keinen Sinn ergibt).

Bitte folgende Fälle mit berücksichtigen:

- Wenn ich eine Dependency angebe, die es nicht gibt, muss ich das im Release Announcement sehen.
- Wenn ich eine Dependency entferne, die ich angegeben habe, muss ich das im Release Announcement sehen.

2020-10-22 05:42 UTC, rrrene commented on src/commands/internal/create-release-announcement.ts
> +export async function getReleaseAnnouncement(mode: string, additionalVersionAnnouncements?: string[]): Promise<string> {
Warum ist diese Datei ein "internes" Kommando, wenn ich das - bspw. im Gegensatz zu `create-changelog` - nicht ausführen kann, sprich hier keine `run`-Funktion definiert ist?

2020-10-22 05:42 UTC, rrrene commented on src/commands/internal/create-release-announcement.ts
> +})}
Das in eine Variable einlesen und gucken, ob diese etwas enthält. Hier werden doch 4 oder 5 Leerzeilen produziert, wenn ich keine Dependency-Changes anfrage, oder?

2020-10-22 05:42 UTC, rrrene commented on src/commands/publish-releasenotes-on-slack.ts
> +--addVersionChange    adds version changes to the changelog, it can be used several times
Zu solchen Nachlässigkeiten fällt mir einfach nichts ein.

![image](https://user-images.githubusercontent.com/311914/96829195-5fed2300-1439-11eb-89b9-faf11e6db62c.png)

2020-10-22 05:42 UTC, rrrene commented on src/commands/publish-releasenotes-on-slack.ts
> +  );
Wieso steht hier dreimal `Usage: ` am Anfang?

![image](https://user-images.githubusercontent.com/311914/96829245-801ce200-1439-11eb-977c-48b3555ebf35.png)

2022-12-21 09:50 UTC, closed without merging